model_id: Qwen/Qwen2.5-VL-3B-Instruct
dataset: Trelis/chess_pieces
batch_size: 1
epochs: 3
lr: 1e-4
grad_accum: 4
devices: 1
strategy: auto
logging_fraction: 0.10
eval_fraction: 0.10
# device_map: "auto"   # leave commented out with Lightning

lora:
  r: 32
  lora_alpha: 16
  lora_dropout: 0.1
  use_rslora: true
  bias: "none"
  task_type: "CAUSAL_LM"
  target_modules:
    - q_proj
    - k_proj
    - v_proj
    - o_proj
    - mlp.0
    - mlp.2
  modules_to_save:
    - lm_head
    - embed_tokens
